= Lots

// TODO Kort beskrive at det er funksjonalitet for å beskrive lots i ESPD.

CAs may for larger contracts choose to devide the contract into lots (sub-contracts).
Lots is used in ESPD to differenciate responses provided by EOs.

Lots are described in procurement documents provided by CA, however a short description is provided inside the ESPD request when used.
The description (constiting of name and description) is used only to choose correct lot(s) in the form when creating the ESPD response.

// TODO Beskrive at kriterier kan bli valgfrie for spesifikke lot basert på angivelse i lot.
//Every lot include selection criteria(s),
//Lots is based on several lot functions, where a lot can include optional criterias.

// The example below illustrate the use of the lots in the ESPD XML document.

// TODO Eksempel (toppen av ESPD) som viser inkludering av Lots.

[source,xml]
.Example of use of the lots in the ESPD XML document.
----
<ext:UBLExtensions> <1>
  <ext:UBLExtension>
    <cbc:ID>urn:fdc:difi.no:2017:vefa:espd:Lots-1</cbc:ID> <2>
    <cbc:Name>Lots description</cbc:Name> <2>
    <ext:ExtensionContent>
      <Lots xmlns="urn:fdc:difi.no:2017:vefa:espd:Lots-1"> <3>
        <VersionID>1.0</VersionID> <4>
        <Lot> <5>
          <ID>lot-01</ID> <6>
          <Title>Fixing roof</Title> <7>
          <OptionalCritierias> <8>
            <ID>e4d37adc-08cd-4f4d-a8d8-32b62b0a1f46</ID>
          </OptionalCritierias>
        </Lot>
        <Lot>
          <ID>lot-02</ID>
          <Title>Gardening</Title>
          <Description>Plant five trees at the driveway.</Description> <9>
        </Lot>
      </Lots>
    </ext:ExtensionContent>
  </ext:UBLExtension>
</ext:UBLExtensions>
----
<1> Using UBL extension to include information about lots.
<2> Identification of extension used for lots.
<3> Lots using XSD Schema provided by Difi.
<4> Version of XSD Schema used, for EHF ESPD is `1.0` used.
<5> A `Lot` element is used to describe a single lot.
<6> Unique identifier (within a single ESPD request) for referencing of a given lot. Must not include empty space or comma (`,`).
<7> Short title describing the lot.
<8> Optional list of criteria identifiers made optional when providing ESPD response for the given lot. Please note only selection criterias may be included in this list.
<9> Optional short description of a given lot to help destinguish the different lots.

// TODO Informere om at de som skal generere ESPD respons _må_ ta med lots fra ESPD forespørsel om den finnes.

Applications generating EHF ESPD Response 1.1 must include the extension providing information about lots when such information is provided in the ESPD request.

ESPD responses for given lots must define the lots using an addition document reference with "LOTS" as document type.

[source,xml]
.Example of lots for which the ESPD response is a response for.
----
<cac:AdditionalDocumentReference>
  <cbc:ID>lot-01</cbc:ID> <1>
  <cbc:DocumentTypeCode listID="ReferencesTypeCodes" listAgencyID="EU-COM-GROW" listVersionID="1.0">LOTS</cbc:DocumentTypeCode> <2>
</cac:AdditionalDocumentReference>
----
<1> Identifier of lot(s) used. In the case of multiple lots must comma (`,`) be used as separator. Empty space may be added (e.g. `lot-01, lot-02`).
<2> Identifying document reference for lots used.

Lots may be used to differenciate selection criterias (not exclusion criterias) for the individual subcontract.
When `OptionalCriterias` is used to provide selection critierias made optional may the producer of ESPD response for the given lot skip answering the optional criteria(s).
In the case of answering for multiple lots in one ESPD response are only those criterias made optional in all selected lots optional.
